version: "3.5"

services:
  # go_ssr_template:
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile.dev
  #   environment:
  #     - DEBUG=true
  #     - DB_NAME=postgres
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USER=postgress
  #     - DB_PASS=password
  #     - HTTP_PORT=3000
  #     - HTTP_ROOT_PATH=/
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  db:
      image: 'postgres:latest'
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: password 
        POSTGRES_DB: go_ssr_template 
      volumes:
        - ./db-mount:/var/lib/postgresql/data/
